### ISSUE TITLE
To-Do List

### ISSUE THREAD

**Issue by SkeletalFish** [SkeletalFish/game-wumpus#1]
- [ ] Complete Cave.validate()
- [ ] Create walk/find function
- [ ] Create map selection function
- [ ] Create map creation function
- [ ] Create main game play loop
